#!/bin/sh

#Command-line options
IFLAG=''
SFLAG=''

#get options
while getopts a:A:his option
do	case "$option" in
	a)
		APIKEY=$OPTARG
		;;
	A)
		APIKEY=$(cat $OPTARG)
		;;
	h)
		echo "Usage: install.sh [-his] [-a <api-key>] [-A <api-key file>]"
		echo "======= Options ========"
		echo "a : Specify your slack api token for setup."
		echo "A : Specify a file containing your api token for setup"
		echo "h : Display this help text and exit."
		echo "i : Install dependancies (will attempt to determine your package manager if necessary, but yum is NOT supported)."
		echo "s : systemd-less install (bot daemon will be placed in /var/www/botd)."
		exit 0
		;;
	i)
		IFLAG='t'
		;;
	s)
		SFLAG='t'
		;;
	[?])
		echo "Try 'install.sh -h' for help"
		exit 1
		;;
	esac
done

#check for proper permissions
if [ $(id -u) -ne 0 ]
then
	if [ $DISPLAY ] && [ $(which gksudo) ]
	then
		gksudo "$0"
		exit 0
	fi
	if [ $(which sudo) ]
	then
		sudo "$0"
		exit 0
	fi
	echo "This script must be run with root permissions, and you don't appear to have sudo so we can't do it ourselves"
	exit 2
fi


#if -i is specified, we must find a package manager
if [ $(which apt-get) ]
then
	PKG='apt'
elif [ $(which pacman) ]
then
	PKG='pac'
else
	echo "-i option was specified, but a suitable package manager could not be found."
	echo "Either install dependancies manually, or continue without the -i option."
	exit 4
fi
	


echo "Checking for dependancies..."

#####################################
###	CHECK FOR DEPENDANCIES    ###
#####################################

#$PATH/python -> */python3
if [ ! $(which python) ] && [ ! $(which python3) ]
then
	if [ -n $IFLAG ]
	then
		echo "You do not appear to have python in your `$PATH`, if you would like us to try to install it run 'install.sh -i', otherwise you must either install it yourself or ensure that it is in your `$PATH`."
		exit 3
	elif [ $PKG = 'apt' ]
	then
		apt-get install python3
	elif [ $PKG = 'pac' ]
	then
		pacman -S python3
	fi
#python is version 3+
elif [ ! $(python --version | sed 's/.*\s//' | sed 's/\..*//') = 3 ]
then
	if [ ! -n $IFLAG ]
	then
		if [ $PKG = 'apt' ]
		then
			apt-get install python3
		elif [ $PKG = 'pac' ]
		then
			pacman -S python3
		fi
	else
		echo "Python is not version 3+, you must link /usr/bin/python to a python3 executable, install python3 and then link, or use the '-i' option."
		exit 3
	fi
fi

echo "\tPython is version 3+..."


#pip is version 3+
if [ ! $(which pip3) ]
then
	if [ ! -n $IFLAG ]
	then
		if [ $PKG = 'apt' ]
		then
			apt-get install python3-pip
		elif [ $PKG = 'pac' ]
		then
			pacman -S python3-pip
		fi
	else
		echo "Pip version 3+ could not be found, you must install pip3 or use the '-i' option."
		exit 3
	fi
fi

echo "\tPip version 3+ found..."


#systemd is installed
if [ ! -d /lib/systemd/system/ ]
then
	if [ -n $SFLAG ]
	then
		echo "You do not have systemd, if you wish to install anyway, run this script with the '-s' option"
		echo "NOTE: bot daemon will be placed in /var/www/slackbot/botd"
		exit 3
	fi
	SYSTEMD='f'
fi

echo "Done."



#Library installation
echo "installing python libraries..."

pip3 install pep3143daemon
pip3 install slacker

echo "Done."

echo "Installing l2p..."
BUILD_DIR=$(mktemp -d)
ORIG_DIR=$(pwd)
cd $BUILD_DIR
wget http://redsymbol.net/static/software/l2p/dist/l2p-1.1.1.tgz
tar -xvf ./l2p-1.1.1.tgz
mv ./l2p-1.1.1/l2p /usr/bin/
cd $ORIG_DIR
rm -rf $BUILD_DIR

echo "Done."

echo "Setting up files and directories..."
#Directory setup
mkdir -p /var/www/slackbot/modules
cp commander.py /var/www/slackbot

echo "Installing modules..."
mkdir -p /var/www/slackbot/modules
touch /var/www/slackbot/modules/__init__.py
for module in  $(ls ./modules); do
	if [ -d "modules/$module" ] && [ ! "$module" = "__pycache__" ]; then
		cd modules/$module
		./install.sh
		cd -
		echo "module $module installed"
	fi
done
echo "...modules installed."

cp botd /var/www/slackbot/
if [ -n $SFLAG ]
then
	cp slackbot.service /lib/systemd/system/
fi
touch /var/log/slackbot.log
touch /var/run/slackbot.pid
mkdir -p /etc/slackbot
if [ ! -z $APIKEY ]
then
	echo $APIKEY > /etc/slackbot/API
else
	touch /etc/slackbot/API
fi

echo "Done."
